### ISSUE TITLE
O conversor de massa não foi incluído no menu principal

### ISSUE THREAD

**Issue by EdeiltonSO** [EdeiltonSO/embarcatech-g8-sub7-dep-ver#11]
O conversor de massa está implementado, mas não é acessível pelo menu principal.

## Correção

1. Renomeie a função `main` no arquivo do conversor;
2. Crie um arquivo de cabeçalho para o conversor;
3. Importe o cabeçalho no `index.c`;
4. Adicione a função no menu principal.

Faça isso em uma branch nova ou na branch `feature/main-menu`.

**Comment by Kuroikenshiga** [comment]
Acabei de fazer um PR com essa funcionalidade

**Comment by EdeiltonSO** [comment]
Obrigado, @Kuroikenshiga!
